AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
  DisplayCopNames: true
  Exclude:
    - bin/*
    - vendor/**/*
    - db/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100
  Exclude:
    - spec/lib/pricing/**/*

Metrics/BlockLength:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2
